project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: program.qmd
        text: Program

format:
  html:
    theme: [cosmo, style.scss]
    toc: true 



